[package]
name = "ham-sdk"
version = "0.6.0"
authors = ["vain0x <vainzerox@gmail.com>"]
edition = "2021"

[dependencies]
ham-core = { path = "../ham-core" }

[lib]
crate-type = ["cdylib"]
doctest = false
