[package]
name = "middle-adapter"
version = "0.1.0"
authors = ["vain0x <vainzerox@gmail.com>"]

[dependencies]
env_logger = { version = "0", default-features = false }
log = "0"
serde = "1"
serde_derive = "1"
serde_json = "1"
